/**
 * Central Rule Registry for CodeLens Static Analysis Engine.
 * Defines rule metadata, categories, severities, and descriptions.
 * 
 * Severity Policy:
 * - CRITICAL: Strong security exposure or dangerous arbitrary code execution.
 * - HIGH: Potential security vulnerability or significant reliability/lifecycle defect.
 * - MEDIUM: Meaningful maintainability, error-containment, or cognitive complexity concern.
 * - LOW: Minor maintainability, style, or performance consideration.
 */

export const RULE_REGISTRY = {
  'SEC-SECRET': {
    rule: 'SEC-SECRET',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'CRITICAL',
    defaultSeverity: 'CRITICAL',
    confidence: 0.98,
    impactWeight: 1.0,
    title: 'Hardcoded credential',
    description: 'Detects plaintext secrets, cryptographic keys, and token literals in source code.',
    recommendation: 'Extract sensitive credentials into environment variables or a secret vault.',
  },
  'SEC-SQLI': {
    rule: 'SEC-SQLI',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'CRITICAL',
    defaultSeverity: 'CRITICAL',
    confidence: 0.85,
    impactWeight: 1.0,
    title: 'Potential SQL injection',
    description: 'Detects dynamic SQL queries constructed with interpolated or concatenated expressions.',
    recommendation: 'Use parameterized queries with driver-supplied bind variables instead of dynamic query strings.',
  },
  'SEC-EVAL': {
    rule: 'SEC-EVAL',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'CRITICAL',
    defaultSeverity: 'CRITICAL',
    confidence: 1.0,
    impactWeight: 1.0,
    title: 'Dangerous use of eval()',
    description: 'Direct invocation of eval() executes arbitrary strings as code.',
    recommendation: 'Refactor to safe JSON parsing or structured data lookups.',
  },
  'SEC-FN-CTOR': {
    rule: 'SEC-FN-CTOR',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.95,
    impactWeight: 0.85,
    title: 'Dynamic code execution via Function constructor',
    description: 'Dynamic function construction possesses execution risks similar to eval().',
    recommendation: 'Use standard lexical functions or declarative dispatch tables.',
  },
  'SEC-DANGEROUS-HTML': {
    rule: 'SEC-DANGEROUS-HTML',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.90,
    impactWeight: 0.85,
    title: 'Potentially unsafe dangerouslySetInnerHTML usage',
    description: 'Direct raw HTML injection bypasses React XSS protections.',
    recommendation: 'Sanitize content with DOMPurify or render standard JSX elements.',
  },
  'COMP-HIGH': {
    rule: 'COMP-HIGH',
    category: 'COMPLEXITY',
    ruleClass: 'MAINTAINABILITY',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.95,
    impactWeight: 0.70,
    title: 'High cyclomatic complexity',
    description: 'Function contains an excessive count of decision points (threshold > 10).',
    recommendation: 'Decompose function into smaller helpers or utilize early returns.',
  },
  'COMP-NESTING': {
    rule: 'COMP-NESTING',
    category: 'COMPLEXITY',
    ruleClass: 'MAINTAINABILITY',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.95,
    impactWeight: 0.70,
    title: 'Excessive control-flow nesting depth',
    description: 'Control flow nesting exceeds the recommended threshold (> 4 levels).',
    recommendation: 'Invert conditional checks with guard clauses to flatten control structures.',
  },
  'QUAL-LENGTH': {
    rule: 'QUAL-LENGTH',
    category: 'QUALITY',
    ruleClass: 'MAINTAINABILITY',
    severity: 'LOW',
    defaultSeverity: 'LOW',
    confidence: 0.55,
    impactWeight: 0.15,
    title: 'Function exceeds recommended line length',
    description: 'Function spans more than 50 source lines.',
    recommendation: 'Refactor into smaller single-responsibility functions.',
  },
  'QUAL-EMPTY-CATCH': {
    rule: 'QUAL-EMPTY-CATCH',
    category: 'QUALITY',
    ruleClass: 'RELIABILITY',
    severity: 'MEDIUM',
    defaultSeverity: 'MEDIUM',
    confidence: 0.90,
    impactWeight: 0.60,
    title: 'Empty catch block suppresses exceptions',
    description: 'Catch block contains no statements, silently hiding failures.',
    recommendation: 'Log the error or provide an explicit fallback recovery path.',
  },
  'QUAL-VAR': {
    rule: 'QUAL-VAR',
    category: 'QUALITY',
    ruleClass: 'MAINTAINABILITY',
    severity: 'LOW',
    defaultSeverity: 'LOW',
    confidence: 0.50,
    impactWeight: 0.10,
    title: "Use of function-scoped 'var' declaration",
    description: "The 'var' keyword introduces function-scoping and hoisting ambiguities.",
    recommendation: "Prefer block-scoped 'const' or 'let' where appropriate.",
  },
  'REACT-INDEX-KEY': {
    rule: 'REACT-INDEX-KEY',
    category: 'QUALITY',
    ruleClass: 'PERFORMANCE',
    severity: 'LOW',
    defaultSeverity: 'LOW',
    confidence: 0.65,
    impactWeight: 0.20,
    title: 'Array index used as React key prop',
    description: 'Using map callback index as key can degrade reconciliation on list mutation.',
    recommendation: 'Use a stable, unique item identifier (e.g., item.id).',
  },
  'REACT-HOOK-DEPS': {
    rule: 'REACT-HOOK-DEPS',
    category: 'QUALITY',
    ruleClass: 'CORRECTNESS',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.85,
    impactWeight: 0.85,
    title: 'Potential missing dependency in useEffect hook',
    description: 'Callback references an outer prop or variable omitted from dependency array.',
    recommendation: 'Add the referenced variable to the dependency array.',
  },
  'PERF-EFFECT-CLEANUP': {
    rule: 'PERF-EFFECT-CLEANUP',
    category: 'PERFORMANCE',
    ruleClass: 'PERFORMANCE',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.85,
    impactWeight: 0.85,
    title: 'Potential missing event-listener cleanup in useEffect',
    description: 'Subscribing to DOM/window events without unregistering on unmount can leak memory.',
    recommendation: 'Return a cleanup function from useEffect that invokes removeEventListener.',
  },
  'QUAL-UNREACHABLE': {
    rule: 'QUAL-UNREACHABLE',
    category: 'QUALITY',
    ruleClass: 'CORRECTNESS',
    severity: 'MEDIUM',
    defaultSeverity: 'MEDIUM',
    confidence: 0.95,
    impactWeight: 0.50,
    title: 'Unreachable code detected',
    description: 'Statements placed after return, throw, break, or continue will never be executed.',
    recommendation: 'Remove redundant statements or fix control flow branches.',
  },
  'QUAL-DUPLICATE-KEYS': {
    rule: 'QUAL-DUPLICATE-KEYS',
    category: 'QUALITY',
    ruleClass: 'CORRECTNESS',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.95,
    impactWeight: 0.80,
    title: 'Duplicate key in object literal',
    description: 'Multiple properties with the same name in an object literal overwrite previous definitions silently.',
    recommendation: 'Remove or rename duplicate object keys.',
  },
  'QUAL-DEBUGGER': {
    rule: 'QUAL-DEBUGGER',
    category: 'QUALITY',
    ruleClass: 'MAINTAINABILITY',
    severity: 'MEDIUM',
    defaultSeverity: 'MEDIUM',
    confidence: 1.0,
    impactWeight: 0.40,
    title: 'Leftover debugger statement in source',
    description: 'Debugger statements halt execution in browser/runtime environments.',
    recommendation: 'Remove debugger statements before deploying to production.',
  },
  'QUAL-EQEQ': {
    rule: 'QUAL-EQEQ',
    category: 'QUALITY',
    ruleClass: 'CORRECTNESS',
    severity: 'LOW',
    defaultSeverity: 'LOW',
    confidence: 0.70,
    impactWeight: 0.20,
    title: 'Use of loose equality (== or !=)',
    description: 'Loose equality performs implicit type coercion which can cause subtle logic bugs.',
    recommendation: 'Use strict equality (=== or !==) instead.',
  },
  'SEC-DEP-WILDCARD': {
    rule: 'SEC-DEP-WILDCARD',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.95,
    impactWeight: 0.80,
    title: 'Wildcard or unrestricted dependency version',
    description: 'Specifying "*" or "latest" allows unvetted upstream releases to execute automatically.',
    recommendation: 'Pin dependency versions using specific semver ranges (e.g. ^1.2.0 or ~1.2.0).',
  },
  'SEC-EJS-UNESCAPED': {
    rule: 'SEC-EJS-UNESCAPED',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'HIGH',
    defaultSeverity: 'HIGH',
    confidence: 0.90,
    impactWeight: 0.85,
    title: 'Unescaped raw output in EJS template',
    description: 'Using <%- outputs unescaped HTML, creating a direct Cross-Site Scripting (XSS) vulnerability if user data is rendered.',
    recommendation: 'Use <%= for HTML-escaped output or sanitize input before rendering.',
  },
  'SEC-INSECURE-HTTP': {
    rule: 'SEC-INSECURE-HTTP',
    category: 'SECURITY',
    ruleClass: 'SECURITY',
    severity: 'MEDIUM',
    defaultSeverity: 'MEDIUM',
    confidence: 0.85,
    impactWeight: 0.50,
    title: 'Insecure HTTP protocol in package configuration',
    description: 'Insecure http:// URLs expose packages to man-in-the-middle tampering.',
    recommendation: 'Use https:// or secure git protocols for repository and registry URLs.',
  },
};

/**
 * Returns clean array of all supported rules for API exposition.
 */
export function getRegisteredRules() {
  return Object.values(RULE_REGISTRY).map((r) => ({
    rule: r.rule,
    category: r.category,
    ruleClass: r.ruleClass || r.category,
    severity: r.severity,
    confidence: r.confidence,
    impactWeight: r.impactWeight,
    title: r.title,
    description: r.description,
    recommendation: r.recommendation,
  }));
}
